module.exports = require('./lib/SyncFunction')
module.exports.SyncFunction = require('./lib/SyncFunction')
module.exports.SyncQueue = require('./lib/SyncQueue')
module.exports.ThroatFunction = require('./lib/ThroatFunction')
module.exports.ThroatQueueFunction = require('./lib/ThroatQueueFunction')
module.exports.TimerFunction = require('./lib/TimerFunction')
module.exports.SyncLite = require('./lib/SyncLite')